[mainConfig]
appName = "GopherAI"
host = "0.0.0.0"
port = 8888

[mysqlConfig]
host = "127.0.0.1"
port = 3306
user = "root"
password = "sql002522"
databaseName = "GopherAI"
charset =  "utf8mb4"

[redisConfig]
host = "127.0.0.1"
port = 6379
password = ""
db = 0

[emailConfig]
authcode = "bllmlbauutccdahf"
email = "1765477265@qq.com"

[jwtConfig]
expire_duration= 168
issuer = "Lisizhe"
subject= "GopherAI"
key= "GopherAI-v2-Lisizhe"

[rabbitmqConfig]
host= "127.0.0.1"
port= 5672
username= "root"
password= "002522"
vhost= "/"

[milvusConfig]
address= "localhost:19530"
databaseName="GopherAI"

[ragConfig]
topK=3